import { useEffect, useMemo, useState } from 'react'
import { Plus, Loader2, Key, AlertCircle } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'
import { useAppStore } from '@/store/appStore'
import { useDatabase } from '@/hooks/useDatabase'

function quoteIdent(name) {
  return '"' + String(name).replace(/"/g, '""') + '"'
}

const AUTO_UDT = new Set(['serial', 'bigserial', 'smallserial'])

function isAutoGenerated(col) {
  if (AUTO_UDT.has(col.udt_name)) return true
  if (col.default_value && /nextval\(/i.test(col.default_value)) return true
  return false
}

function isNumericType(col) {
  return /^(int|float|numeric|real|double|smallint|bigint)/i.test(col.udt_name)
}

function isBooleanType(col) {
  return col.udt_name === 'bool' || col.type === 'boolean'
}

function isJsonType(col) {
  return col.udt_name === 'json' || col.udt_name === 'jsonb'
}

function isTimestampType(col) {
  return /timestamp/i.test(col.udt_name) || /timestamp/i.test(col.type)
}

function isDateType(col) {
  return col.udt_name === 'date'
}

function defaultValueForInput(col) {
  if (isAutoGenerated(col)) return { mode: 'default', value: '' }
  if (col.default_value) return { mode: 'default', value: '' }
  if (col.nullable) return { mode: 'null', value: '' }
  return { mode: 'value', value: isBooleanType(col) ? 'false' : '' }
}

export function InsertRowDialog({ schema, table, columns, onInserted }) {
  const { insertRowDialogOpen, setInsertRowDialogOpen, showToast } = useAppStore()
  const { activeConnection } = useDatabase()

  const [values, setValues] = useState({})
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    if (insertRowDialogOpen && columns?.length) {
      const init = {}
      for (const col of columns) init[col.name] = defaultValueForInput(col)
      setValues(init)
      setSubmitting(false)
    }
  }, [insertRowDialogOpen, columns])

  const setCol = (name, patch) => {
    setValues((v) => ({ ...v, [name]: { ...v[name], ...patch } }))
  }

  const handleSubmit = async () => {
    if (!activeConnection || !schema || !table) return

    const cols = []
    const placeholders = []
    const params = []
    let idx = 1

    for (const col of columns) {
      const state = values[col.name]
      if (!state || state.mode === 'default') continue

      cols.push(quoteIdent(col.name))
      if (state.mode === 'null') {
        placeholders.push('NULL')
      } else {
        placeholders.push(`$${idx++}`)
        let v = state.value
        if (isBooleanType(col)) {
          v = v === 'true' || v === true
        } else if (isNumericType(col) && v !== '') {
          const n = Number(v)
          if (Number.isNaN(n)) {
            showToast(`Invalid number for ${col.name}`, 'warning')
            return
          }
          v = n
        } else if (isJsonType(col) && v) {
          try {
            JSON.parse(v)
          } catch {
            showToast(`Invalid JSON for ${col.name}`, 'warning')
            return
          }
        }
        params.push(v === '' && col.nullable ? null : v)
      }
    }

    const sql =
      cols.length === 0
        ? `INSERT INTO ${quoteIdent(schema)}.${quoteIdent(table)} DEFAULT VALUES`
        : `INSERT INTO ${quoteIdent(schema)}.${quoteIdent(table)} (${cols.join(', ')}) VALUES (${placeholders.join(', ')})`

    setSubmitting(true)
    try {
      await window.gamalab.db.query(activeConnection.id, sql, params)
      showToast('Row inserted', 'success')
      setInsertRowDialogOpen(false)
      onInserted?.()
    } catch (err) {
      showToast(err.message, 'error')
    } finally {
      setSubmitting(false)
    }
  }

  const title = `Insert into ${schema}.${table}`

  return (
    <Dialog
      open={insertRowDialogOpen}
      onOpenChange={(o) => !submitting && setInsertRowDialogOpen(o)}
    >
      <DialogContent className="max-h-[85vh] sm:max-w-xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Plus className="h-5 w-5 text-lab-blue" />
            Insert row
          </DialogTitle>
          <DialogDescription className="font-mono text-xs">{title}</DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[55vh] pr-2">
          <div className="flex flex-col gap-3">
            {columns?.map((col) => {
              const state = values[col.name] || { mode: 'value', value: '' }
              const auto = isAutoGenerated(col)
              const hasDefault = !!col.default_value && !auto
              return (
                <div
                  key={col.name}
                  className={cn(
                    'flex flex-col gap-1.5 rounded-md border border-border bg-muted/20 p-2.5',
                    state.mode === 'null' && 'opacity-70',
                    auto && 'opacity-60'
                  )}
                >
                  <div className="flex items-center justify-between gap-2">
                    <Label className="flex items-center gap-1.5 text-xs">
                      {col.is_primary_key && <Key className="h-3 w-3 text-lab-orange" />}
                      <span className="font-semibold">{col.name}</span>
                      <span className="font-mono text-[10px] font-normal text-muted-foreground">
                        {col.udt_name}
                      </span>
                      {!col.nullable && !auto && (
                        <span className="text-[10px] text-destructive">NOT NULL</span>
                      )}
                    </Label>
                    <div className="flex gap-1">
                      {hasDefault && (
                        <button
                          type="button"
                          onClick={() => setCol(col.name, { mode: 'default', value: '' })}
                          className={cn(
                            'rounded border px-1.5 py-0.5 text-[9px] uppercase tracking-wider transition-colors',
                            state.mode === 'default'
                              ? 'border-lab-blue bg-lab-blue/15 text-lab-blue'
                              : 'border-border text-muted-foreground hover:text-foreground'
                          )}
                        >
                          default
                        </button>
                      )}
                      {col.nullable && (
                        <button
                          type="button"
                          onClick={() => setCol(col.name, { mode: 'null', value: '' })}
                          className={cn(
                            'rounded border px-1.5 py-0.5 text-[9px] uppercase tracking-wider transition-colors',
                            state.mode === 'null'
                              ? 'border-muted-foreground bg-muted/60 text-foreground'
                              : 'border-border text-muted-foreground hover:text-foreground'
                          )}
                        >
                          null
                        </button>
                      )}
                      <button
                        type="button"
                        onClick={() =>
                          setCol(col.name, {
                            mode: 'value',
                            value: state.value || (isBooleanType(col) ? 'false' : ''),
                          })
                        }
                        className={cn(
                          'rounded border px-1.5 py-0.5 text-[9px] uppercase tracking-wider transition-colors',
                          state.mode === 'value'
                            ? 'border-lab-green bg-lab-green/15 text-lab-green'
                            : 'border-border text-muted-foreground hover:text-foreground'
                        )}
                        disabled={auto}
                      >
                        value
                      </button>
                    </div>
                  </div>

                  {auto ? (
                    <div className="rounded border border-dashed border-border px-2 py-1.5 text-[11px] italic text-muted-foreground">
                      auto-generated (skip)
                    </div>
                  ) : state.mode === 'default' ? (
                    <div className="rounded border border-dashed border-border bg-background px-2 py-1.5 font-mono text-[11px] text-muted-foreground">
                      uses default: {col.default_value}
                    </div>
                  ) : state.mode === 'null' ? (
                    <div className="rounded border border-dashed border-border bg-background px-2 py-1.5 text-[11px] italic text-muted-foreground">
                      NULL
                    </div>
                  ) : isBooleanType(col) ? (
                    <select
                      value={state.value}
                      onChange={(e) => setCol(col.name, { value: e.target.value })}
                      className="h-8 rounded border border-input bg-background px-2 text-xs focus:outline-none focus:ring-1 focus:ring-ring"
                      disabled={submitting}
                    >
                      <option value="false">false</option>
                      <option value="true">true</option>
                    </select>
                  ) : isJsonType(col) ? (
                    <textarea
                      value={state.value}
                      onChange={(e) => setCol(col.name, { value: e.target.value })}
                      placeholder={'{"key": "value"}'}
                      rows={3}
                      disabled={submitting}
                      className="rounded border border-input bg-background p-2 font-mono text-xs focus:outline-none focus:ring-1 focus:ring-ring"
                    />
                  ) : isDateType(col) ? (
                    <Input
                      type="date"
                      value={state.value}
                      onChange={(e) => setCol(col.name, { value: e.target.value })}
                      disabled={submitting}
                      className="h-8 text-xs"
                    />
                  ) : isTimestampType(col) ? (
                    <Input
                      type="datetime-local"
                      value={state.value}
                      onChange={(e) => setCol(col.name, { value: e.target.value })}
                      disabled={submitting}
                      className="h-8 text-xs"
                    />
                  ) : (
                    <Input
                      type={isNumericType(col) ? 'number' : 'text'}
                      value={state.value}
                      onChange={(e) => setCol(col.name, { value: e.target.value })}
                      placeholder={isNumericType(col) ? '0' : ''}
                      disabled={submitting}
                      className="h-8 font-mono text-xs"
                    />
                  )}
                </div>
              )
            })}
          </div>
        </ScrollArea>

        <DialogFooter>
          <Button
            variant="ghost"
            onClick={() => setInsertRowDialogOpen(false)}
            disabled={submitting}
          >
            Cancel
          </Button>
          <Button variant="lab" onClick={handleSubmit} disabled={submitting}>
            {submitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Inserting…
              </>
            ) : (
              <>
                <Plus className="h-4 w-4" />
                Insert row
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
